# Generated by Django 3.1.6 on 2021-03-01 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_category_service_servicetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='location',
            field=models.CharField(choices=[('Remotely', 'Удаленно'), ("Student's home", 'У ученика'), ("Tutor's home", 'У преподавателя'), ('Any', 'Любое')], default='Any', max_length=200),
        ),
    ]
