# Generated by Django 3.1.6 on 2021-03-01 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_auto_20210301_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='types',
            field=models.ManyToManyField(null=True, to='userprofile.ServiceType'),
        ),
    ]
