# Generated by Django 3.1.6 on 2021-03-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_auto_20210301_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='types',
            field=models.ManyToManyField(default=[], to='userprofile.ServiceType'),
        ),
    ]
