# Generated by Django 3.1.6 on 2021-03-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0009_auto_20210301_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='name',
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
