# Generated by Django 3.1.6 on 2021-03-10 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0010_auto_20210310_0806'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status1', models.CharField(choices=[('blocked', 'Заблокирован'), ('Match', 'Совпадение'), ('Like', 'Понравился'), ('Archived', 'Архивирован')], max_length=200, null=True)),
                ('status2', models.CharField(choices=[('blocked', 'Заблокирован'), ('Match', 'Совпадение'), ('Like', 'Понравился'), ('Archived', 'Архивирован')], max_length=200, null=True)),
                ('service1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='userprofile.service')),
                ('service2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='userprofile.service')),
            ],
        ),
    ]
