# Generated by Django 3.1.6 on 2021-03-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0011_relation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='location',
            field=models.CharField(choices=[('Remotely', 'Удаленно'), ("Student's home", 'У ученика'), ("Tutor's home", 'У преподавателя')], default='Any', max_length=200),
        ),
    ]
