# Generated by Django 3.1.6 on 2021-04-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0015_auto_20210409_1214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dialog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-datetime']},
        ),
        migrations.AddField(
            model_name='message',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
